// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myproj.Models;

public partial class Group
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int IdDepartment { get; set; }

    public virtual Department IdDepartmentNavigation { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}