// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myproj.Models;

public partial class SCard
{
    public int Id { get; set; }

    public int IdStudent { get; set; }

    public int IdBook { get; set; }

    public string DateOut { get; set; }

    public string DateIn { get; set; }

    public int IdLibrarian { get; set; }

    public virtual Book IdBookNavigation { get; set; }

    public virtual Librarian IdLibrarianNavigation { get; set; }

    public virtual Student IdStudentNavigation { get; set; }
}