// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace myproj.Models;

public partial class Student
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int IdGroup { get; set; }

    public int? Term { get; set; }

    public virtual Group IdGroupNavigation { get; set; }

    public virtual ICollection<SCard> SCards { get; set; } = new List<SCard>();
}